# SwiftLint version 0.11.1

disabled_rules: # rule identifiers to exclude from running
  - todo
  - valid_docs
  - operator_whitespace
  - opening_brace
  - conditional_binding_cascade
  - colon    # Cannot customize to allow ClassName : Superclass
  - mark
opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_unwrapping

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Vendor
  - build
  - Resources
  - AppDelegate.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
trailing_whitespace: 
    ignores_empty_lines: 1
statement_position:
    statement_mode: uncuddled_else
line_length:
    warning: 130
    error: 135
force_cast: error
force_try: error
force_unwrapping: error
variable_name:
  max_length:
    warning: 55
    error: 60
  min_length:
    error: 4
  excluded:
    - row
    - key
    - id
    - url
    - uri
    - db
    - bar
    - red
    - lhs
    - rhs
    - tag
    - rs
    - URI
    - URL
    - new
    - old
    - to
trailing_newline: error
comma: error
empty_count: error
legacy_constructor: error
legacy_constant: error
trailing_semicolon: error

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)

custom_rules:
   comments_space:
      name: "Space After Comment"
      regex: "(^ *//(?!(MARK|swiftlint|FIXME|TODO))\w+)"
      message: "There should be a space after //"
      severity: error
   empty_first_line:
      name: "Empty First Line"
      regex: "(^[ a-zA-Z ]*(?:protocol|extension|class|struct) (?!(?:var|let))[ a-zA-Z:]*\{\n *\S+)"
      message: "There should be an empty line after a declaration"
      severity: error
   empty_line_after_super:
      name: "Empty Line After Super"
      regex: "(^ *super\.[ a-zA-Z0-9=?.\(\)\{\}:,><!]*\n *(?!(?:\}|return))\S+)"
      message: "There should be an empty line after super"
      severity: error
   multiple_empty_lines:
      name: "Multiple Empty Lines"
      regex: "((?:\s*\n){3,})"
      message: "There are too many line breaks"
      severity: error